name = "ravan-english-bot"
main = "src/index.ts"
compatibility_date = "2024-09-01"

[vars]
TELEGRAM_WEBHOOK_SECRET = "ravan_english"

[[d1_databases]]
binding = "DB"
database_name = "ravan_english_local"
database_id = "aeead8fa-8703-415d-b387-0e9d69e92a83"
 [triggers]
crons = ["0 * * * *"] # اجرا در دقیقه صفر هر ساعت (هر یک ساعت یک بار)
 
